name: fundoc
# https://github.com/CSSSR/fundoc-action

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  fundoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: generate introduction
        run: |
          make introduction.md

      - name: Fundoc Action
        uses: daynin/fundoc-action@v0.2.1

      - name: update highlight.js
        run: |
          ls -lisa ./docs_resources ./docs
          sudo cp ./docs_resources/highlight.js ./docs/highlight.js
          sudo rm stroeer/introduction.md book.toml || true

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: generate documentation'
          # bypass branch protection
          push_options: '--force'
