name: Publish package to GitHub Packages
on:
  release:
    types: [published, edited]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Proto
        run: ./install_proto.sh
      - name: npm install
        run: npm install
        working-directory: node
      - name: make protoc
        run: make PROTOC_BIN=./bin/protoc all
      - name: Publish to GitHub Packages
        run: ./gradlew clean publish
        working-directory: java
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: npm test
        run: npm test
      - name: npm publish
        run: |
          npm version $RELEASE_TAG
          npm publish
        working-directory: node
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
